---
title: "Web Scraper"
output: html_notebook
params:
  nb_id: "001"
---


```{r load packages}

packages = c('rmarkdown', 'plyr', 'dplyr','ggplot2', 'readr', 'tidyr', 'stringr',  'knitr', 'sparklyr', 'shiny', 'data.table', 'zoo','fasttime',"twitteR","openssl","httpuv" , 'rvest', 'httr','jsonlite','lubridate', 'twitteR')

package.check <- lapply(packages, FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
        install.packages(x, dependencies = TRUE)
        library(x, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
    }
})


```




```{r testing rvest}

# pull in some html

nsmb <- read_html("https://www.nature.com/nsmb/volumes/25/issues/10") 

# https://www.nature.com/nsmb/volumes/25/issues/10

```




```{r}


nsmb %>% rvest::html_text()

```






```{r}

nsmb %>% html_node(paste0(".pb30:nth-child(1) a")) %>% html_text()


nsmb %>% html_node(paste0(".pb30:nth-child(2) a")) %>% html_text()



nsmb %>% html_node(paste0(".pb30:nth-child(7) a")) %>% html_text()



```






```{r}

# testing cleaning up text
nsmb %>% html_node(paste0(".pb30:nth-child(7) a")) %>% html_text2()


```





```{r }

#function to pull out subjournal, volume and issue information

subjournal <- "nsmb"

subjournal_html_parser <- function(subjournal = "nsmb",volume = 1,issue = 1,child_node = 1) {
          tmp_html <- read_html(paste0("https://www.nature.com/",subjournal,"/volumes/",volume,"/issues/",issue))
          
          
          # parse html text
          parsed_title <- tmp_html %>% html_node(paste0(".pb30:nth-child(",child_node,") a")) %>% html_text2()
          bind_cols(subjournal = subjournal,
                    volume = volume,
                    issue = issue,
                    parsed_title = parsed_title)
}


subjournal_html_parser(subjournal = "nsmb",volume = 1,issue = 1,child_node = 7) 


```




```{r}

# messing around with lapply 


tictoc::tic()
test_list <- lapply(1:2, subjournal_html_parser, subjournal = "nsmb", issue = c(1,2), volume = 1)
tictoc::toc()

bind_rows(test_list)





```



```{r}
tictoc::tic()
test  <- mapply(subjournal_html_parser, child_node = 1:20, issue = c(1,2), subjournal = "nsmb",volume = 1) 
tictoc::toc()
test2 <- test %>% data.frame(.) %>% t()

bind_rows(test)

#,newcol = c("subjournal","volume","issue","title")
```





```{r}


loop_list <- 1:20

nsmb_test <- as.character()
nsmb_test_link <- as.character()

nature_data <- function(loop_vect) {
  
  
    #article title
nsmb_node <-  nsmb %>% html_node(paste0(".pb30:nth-child(",{{loop_vect}},") a")) %>% html_text()  %>% 
        # Trim additional white space
        str_trim() %>%                       
        # Convert the list into a vector
        unlist()

nsmb_t0 <- str_trim(sapply(strsplit(nsmb_node, "\n"), "[", 1)) 

nsmb_test <- rbind(nsmb_test, nsmb_t0)


# article link
nsmb_node_link <-  nsmb %>% html_node(paste0(".pb30:nth-child(",{{loop_vect}},") a")) %>% html_attr('href')  %>% 
        # Trim additional white space
        str_trim() %>%                       
        # Convert the list into a vector
        unlist()

nsmb_t0_link <- str_trim(nsmb_node_link) 

nsmb_test_link <- rbind(nsmb_test_link, nsmb_t0_link)


nsmb2_link <- nsmb_test_link %>% data.frame() %>% transmute(link = (paste0("https://www.nature.com",.)))
row.names(nsmb2_link) <- NULL

nsmb2 <- nsmb_test %>% data.frame() %>% dplyr::rename(.,"title" = ".")
row.names(nsmb2) <- NULL

nsmb3 <- cbind(nsmb2,nsmb2_link,issue,volume) %>% mutate(nchar_title = nchar(as.character(title)),
                                            nchar_link  = nchar(link),
                                            nchar_total = nchar(as.character(title)) + nchar(link))
print(nsmb3)
}

nature_data(loop_list)

lop_dat <- lapply(loop_list, nature_data)


nsmb2_link <- nsmb_test_link %>% data.frame() %>% transmute(link = (paste0("https://www.nature.com",.)))
row.names(nsmb2_link) <- NULL

nsmb2 <- nsmb_test %>% data.frame() %>% dplyr::rename(.,"title" = ".")
row.names(nsmb2) <- NULL

nchar(as.character(nsmb2$title))

nsmb3 <- cbind(nsmb2,nsmb2_link,issue,volume) %>% mutate(nchar_title = nchar(as.character(title)),
                                            nchar_link  = nchar(link),
                                            nchar_total = nchar(as.character(title)) + nchar(link))


```



```{r}
nsmb_1 <- nsmb %>% html_node(paste0(".pb30:nth-child(",1,") a")) %>% html_text()   %>% 
        # Trim additional white space
        str_trim() %>%                       
        # Convert the list into a vector
        unlist()

nsmb_1
nsmb_t0 <- str_trim(sapply(strsplit(nsmb_1, "\n"), "[", 1)) 

nsmb_t0
```

```{r artcile title}

loop_list <- 1:20

nsmb_test <- as.character()
nsmb_test_link <- as.character()


for (loop in loop_list){
  #article title
nsmb_node <-  nsmb %>% html_node(paste0(".pb30:nth-child(",loop,") a")) %>% html_text()  %>% 
        # Trim additional white space
        str_trim() %>%                       
        # Convert the list into a vector
        unlist()

nsmb_t0 <- str_trim(sapply(strsplit(nsmb_node, "\n"), "[", 1)) 

nsmb_test <- rbind(nsmb_test, nsmb_t0)


# article link
nsmb_node_link <-  nsmb %>% html_node(paste0(".pb30:nth-child(",loop,") a")) %>% html_attr('href')  %>% 
        # Trim additional white space
        str_trim() %>%                       
        # Convert the list into a vector
        unlist()

nsmb_t0_link <- str_trim(nsmb_node_link) 

nsmb_test_link <- rbind(nsmb_test_link, nsmb_t0_link)



}

nsmb2_link <- nsmb_test_link %>% data.frame() %>% transmute(link = (paste0("https://www.nature.com",.)))
row.names(nsmb2_link) <- NULL

nsmb2 <- nsmb_test %>% data.frame() %>% dplyr::rename(.,"title" = ".")
row.names(nsmb2) <- NULL

nchar(as.character(nsmb2$title))

nsmb3 <- cbind(nsmb2,nsmb2_link,issue,volume) %>% mutate(nchar_title = nchar(as.character(title)),
                                            nchar_link  = nchar(link),
                                            nchar_total = nchar(as.character(title)) + nchar(link))


nsmb4 <- nsmb3 %>% mutate(hashtag = "#structuralbio #nsmb #biophysics @nature @NatureSMB",
                          tweet_text = paste0(hashtag," ",link),
                          nchar_tweet = nchar(as.character(tweet_text))) %>%
                   filter(is.na(title) != T)

nsmb4

#rm(loop, loop_list, nsmb_test,nsmb_t0, nsmb_node, nsmb_node_link, nsmb_t0_link, nsmb_test_link, nsmb2_link, nsmb2, nsmb3)
```







































