---
title: "Web Scraper Data Pull"
output: html_notebook
params:
  nb_id: "002"
---


```{r load packages}

packages = c('rmarkdown', 'plyr', 'dplyr','ggplot2', 'readr', 'tidyr', 'stringr',  'knitr', 'sparklyr', 'shiny', 'data.table', 'zoo','fasttime',"twitteR","openssl","httpuv" , 'rvest', 'httr','jsonlite','lubridate', 'twitteR','magrittr')

package.check <- lapply(packages, FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
        install.packages(x, dependencies = TRUE)
        library(x, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
    }
})

library(tidyverse)
```


```{r load poc scripts}


nature_html_parser <- read_rds(here::here("2. Data",paste0("001","_nature_html_parser.rds")))


cmapply <- readr::read_rds(here::here("2. Data", paste0("001","_cmapply.rds")))


journal_code_vector <- readr::read_rds(here::here("2. Data", paste0("001","_journal_code_vector.rds")))



journal_code_vector <- journal_code_vector[journal_code_vector!="nsmb"]
journal_code_vector <- journal_code_vector[journal_code_vector!="nataging"]
journal_code_vector <- journal_code_vector[journal_code_vector!="natastron"]

journal_code_vector <- c("ncb","nchem","ngeo","ni","nm","nmeth","nnano","nphoton","nplants")
```



```{r pull article data}


# get article
# it is not as  efficient as I would like but then again I am webscrapping almost 30 years of article titles
# maybe some type of multithread would be good here
article_combination_list <- cmapply(issue = 1:12, child_node = 1:15, 
                                    subjournal = journal_code_vector,volume = 1:50, FUN=nature_html_parser) 

```


```{r}

write_rds(article_combination_list, here::here("2. Data",paste0(params$nb_id,"_parsed-articles.rds")))


```





```{r}

# df <- list.files(path = "C:/Users/donal/Documents/Projects/DAS0000 - nature webscraper/2. Data/Parsed Data",
#                  pattern = ".rds") %>%
#        map_dfr(readRDS)
# 
# df
parsed_articles <- bind_rows(
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nataging.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natastron.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natbiomedeng.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natcancer.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natcardiovascres.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natcatal.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natcomputsci.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natecolevol.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natelectron.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natfood.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nathumbehav.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natmachintell.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natsustain.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_natsynth.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nbt.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_ncb.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nchem.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nchembio.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nclimate.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nenergy.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_neuro.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_ng.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_ngeo.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_ni.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nm.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nmat.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nmeth.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nmicrobiol.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nnano.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nphoton.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nphys.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nplants.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nprot.rds")),
                             readr::read_rds(here::here("2. Data","Parsed Data","002_nsmb.rds")))


cleaned <- parsed_articles %>% filter(!is.na(parsed_title)) %>%
           dplyr::select(subjournal,date,issue,parsed_title)

write_rds(cleaned, here::here("2. Data",paste0(params$nb_id,"_parsed-articles.rds")))


head(cleaned)
```


```{r}

# journal_code_vector
# 
# 
# for (variable in journal_code_vector) {
#   
#   
# article_list <- cmapply(issue = 1:12, child_node = 1:15, subjournal = {{variable}},volume = 1:50, FUN=nature_html_parser) 
# 
# write_rds(article_list, here::here("2. Data",paste0(params$nb_id,"_",variable,".rds")))
# 
# 
# }
# 


```

